services:
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "4080:1080"
      - "4025:1025"
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=show_me
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  localstack:
    image: localstack/localstack:0.10.6
    ports:
      - "4566:4566"
      - "8082:8082"
    environment:
      - SERVICES=s3:4566
      - HOSTNAME_EXTERNAL=localhost
      - DEBUG=1
      - PORT_WEB_UI=8082
      - AWS_DEFAULT_REGION=eu-north-1
      - AWS_SECRET_ACCESS_KEY=KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      - AWS_ACCESS_KEY_ID=AAAAAAAAAAAAAAAAAAAA
    volumes:
      - ./localstack/:/docker-entrypoint-initaws.d/

volumes:
  db: