spring:
  application:
    name: showme
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/show_me
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 4025
#  servlet:
#    multipart:
#      max-file-size: 10MB

app:
  path: http://localhost:8080
  security:
    jwt:
      access:
        secret: JWT_ACCESS_TOKEN_SECRET
        expiration-ms: 86400000
  aws:
    s3:
      path: http://localhost:4566
      access-key: AAAAAAAAAAAAAAAAAAAA
      secret-key: KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK
      bucket-name: showme
      region: eu-north-1